### ISSUE TITLE
Forgotten C++: `<valarray>`

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#122]

**Comment by lefticus** [comment]
https://compiler-explorer.com/z/jrcG4M4c3

https://en.cppreference.com/w/cpp/numeric/valarray

**Comment by fcolecumberri** [comment]
There is something I don't understand about valarrays operators. for example the operators from https://en.cppreference.com/w/cpp/numeric/valarray/operator_arith3:

```c++
template< class T >
std::valarray<T> operator+
( const std::valarray<T>& lhs, const std::valarray<T>& rhs);

template< class T >
std::valarray<T> operator*
( const std::valarray<T>& lhs, const std::valarray<T>& rhs);
```

this will work fine if `T=int`. However if `T=std::string` now only the `+` will work and if you try to use `std::string` and the `*` operator there will be an uber-cryptic message.

The cryptic part starts with the fact that this works:

```c++
#include <valarray>
#include <string>
#include <iostream>

int main()
{
    std::valarray<std::string> array = {"1", "2"};
    auto product = array*array;
    return 0;
}
```

But at the moment you want to do something like this:

```c++
#include <valarray>
#include <string>
#include <iostream>

int main()
{
    std::valarray<std::string> array = {"1", "2"};
    auto product = array*array;
    std::cout << product[0];
    return 0;
}
```

now at `std::cout << product[0];` it fails because the `error: no match for 'operator*'...` which makes no sense since the operator is not there.

I would assume this would be the perfect place to use the `requires` and change the operators to something like (This part might be wrong redacted, I just want to explain the point):

```c++
template< class T >
std::valarray<T> operator+
( const std::valarray<T>& lhs, const std::valarray<T>& rhs)
requires requires{lhs[0]+rhs[0];}

template< class T >
std::valarray<T> operator*
( const std::valarray<T>& lhs, const std::valarray<T>& rhs)
requires requires{lhs[0]*rhs[0];}
```

Also I know that `requires requires` is a code smell, I am just explaining the main idea.

**Comment by lefticus** [comment]
It's because you are assigning it to an `auto` that you are seeing this behavior where you are seeing it.

The implementation is not doing exactly what the standard says - it's returning a new type that does a multiplication, lazily. 

So you can get something kind of awesome, like this: https://compiler-explorer.com/z/Eo9vnvKsa

I would agree that a requirement that the types actually be applied to the operator sounds like a good requirement. That's part of what makes `<valarray>` "forgotten" C++

**Comment by lefticus** [comment]
Coming in Ep367

**Comment by eteran** [comment]
@fcolecumberri The type you give to `valarray` **must** be a numeric type. Honestly surprised you didn't just get a compile error based on a static assert or similar.
