### ISSUE TITLE
A better main()?

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#209]
We want a better main. Using `int` and `const char **` is problematic. How can we address this issue?

**Comment by fcolecumberri** [comment]
There should be an option to:

```c++
int main(std::span<std::string_view> args)
```

It would be nice.

**Comment by lefticus** [comment]
That is the general idea of the episode, yeah. I need to finish up the example I was working on... hopefully I didn't lose it....

something like:

```cpp
#include <array>
#include <span>
#include <string_view>


constexpr std::span<std::string_view> start(int argc, char** argv) {
  static std::array<std::string_view, 255> argvElements = []() -> std::array<std::string_view, 255> {
    std::array<std::string_view, 255> argvElements;
    for (std::size_t i = 0; i < argc; ++i) {
      argvElements[i] = argv[i];
    }
    return argvElements;
  }();

  return argvElements;
}

int better_main(std::span<std::string_view> args);


int main(int argc, const char *argv[]) {
  return start(argc, argc, better_main);
}
```

**Comment by JohelEGP** [comment]
Maybe it'd be better to create a model of `std::ranges::range` for this use-case, considering the `255` limit of that example.

**Comment by JohelEGP** [comment]
Here's an example: https://compiler-explorer.com/z/nncxsn7Pa.
```C++
#include <ranges>
#include <span>
#include <string_view>
#include <boost/hana/core/make.hpp>

constexpr std::ranges::random_access_range auto start(int argc, char** argv) {
  return std::span(argv, argv + argc) |
    std::views::transform(
      boost::hana::make<std::string_view>
    );
}

using better_main_args = decltype(start(0, nullptr));

int better_main(better_main_args) {
  return 0;
}

int main(int argc, char *argv[]) {
  return better_main(start(argc, argv));
}
```

**Comment by fcolecumberri** [comment]
> ```c++
> 
> constexpr std::span<std::string_view> start(int argc, char** argv) {
> ```

Maybe this is me not having a clue about `constexpr`, but I am almost sure you using `argv` on a `constexpr` environment won't do a thing since you can't know the running arguments at compile time.

Here is my guess:

```c++
#include <iostream>
#include <span>
#include <vector>
#include <memory_resource>

int start(std::span<std::string_view> args){
    //*
    for (const auto & arg : args){
        std::cout << arg << ' ';
    }
    std::cout << "\n";
    //*/
    return 0;
}

int main(int argc, char *argv[]){
    std::array<std::byte, 512> buffer;
    std::pmr::monotonic_buffer_resource mbr{buffer.data(), buffer.size()};
    std::pmr::polymorphic_allocator<std::string_view> pa{&mbr};
    std::pmr::vector<std::string_view> args{pa};
    args.reserve(size_t(argc));
    for(int i=0; i<argc; i++){
        args.push_back(argv[i]);
    }
    return start(args);
}
```

**Comment by JohelEGP** [comment]
> Maybe this is me not having a clue about `constexpr`, but I am almost sure you using `argv` on a `constexpr` environment won't do a thing since you can't know the running arguments at compile time.

That's right. But `start` can be tested at compile-time.

**Comment by lefticus** [comment]
Here's a slightly modified idea: https://compiler-explorer.com/z/5eMqEea89

**Comment by zencatalyst** [comment]
> Here's a slightly modified idea: https://compiler-explorer.com/z/5eMqEea89

I don't think it's standard compliant to modify the parameter list of main. You have added several consts to the parameters. I think those shouldn't be there. Instead they should be in the parameter list of `start`. Inside main we can create a span of string views and pass it to `start`. And `start` can even use the `.subspan(1)` method to create another span that doesn't contain the first command line argument (which is usually the name of the program).

**Comment by milasudril** [comment]
Simply wrapping the arguments in string_views isn't adding any additional value. The complex part in reading command line argument is to do the actual parsing. I think a better main should have the signature

```c++
std::process_exit_status main(std::flatmap<std::string, std::vector<std::string>>&&);
```

A few notes:

* It is not possible to use std::string_view because it is incompatible with C API:s (information about any null terminator is dropped)

* `process_exit_status` is an implementation defined type. On POSIX, it should be able to hold 8 bits. I think on Windows it should be able to hold 32 bits.

* Use `&&` here to make it clear that the runtime is no longer interested in the content of this map

* An even more sophisticated main could be possible with increased reflection capabilities [Reflection-TS], or by providing a *program option container* to the compiler. In the latter case, the runtime could look like

    ```c++
    template<class ProgramOptionContainer>
    std::process_exit_status __run_program(int argc, char** argv)
    {
      ProgramOptionContainer opts{};
      while(argc != 0 && *argv != nullptr)
      {
        // Parsing logic following suitable RFC or ISO/IEC standards
        //...
        opts.insert(key, value);
        --argv;
        ++argv;
      }

      // For brevity, I go for the ADL option here, but maybe a template specialization would be
      // a more appropriate choice.
      return run_program(std::forward<ProgramOptionContainer>(opts));
    }

    int main(int argc, char** argv)
    {
        return static_cast<int>(start_program<__program_option_container>(argc, argv));
    }
    ```
 
  The application code could look something like
  
  ```c++
  #include <main>
  
  std::process_exit_status  run_program(YourContainer&& foo)
  {
     // ...
     return std::process_exit_status::success;
  }
  ```

  This can actually be implemented today like so
  ```bash
  g++ -D__program_option_container=YourContainer main.cpp
  ```

  But it would be cleaner with a dedicated compiler option.

**Comment by Swat-SomeBug** [comment]
How about having a properly named type for this purpose? Which can potentially be standardized and zero overhead?

```c++
#include <string_view>
#include <string>
#include <span>

class Bundle {
private:
    char const* const* argv_;
    std::ptrdiff_t argc_;
public:
    Bundle(char const* const* argv, int argc):
        argv_{argv}, argc_{static_cast<std::ptrdiff_t>(argc)} {

    }

    auto operator[](std::ptrdiff_t idx) const noexcept -> std::string_view {
        return {*std::next(argv_, idx)};
    }
};

int main(int const argc, char const* const* const argv) {

    [[nodiscard]] int better_main(Bundle) noexcept;
    return better_main({argv, argc});
}

int better_main([[maybe_unused]] Bundle args) noexcept {
    // Grab args for any sort of processing
    std::string ar1{args[0]};
    return ar1.size();
}
```

**Comment by eteran** [comment]
Gotta be honest, I really don't see what the real benefit of using this is:

```
return {*std::next(argv_, idx)};
```

over something simple like this:

```
return { argv[idx] };
```

We **know** the type of `argv` to be `char **` so we know that `std::next` is going to basically evaluate to a simple `+`  operator. So why the abstraction? I don't really feel like it makes anything more clear given that array indexing is pretty common.

**Comment by Swat-SomeBug** [comment]
> return { argv[idx] };

@eteran, sure this works as well. `Bundle` must also have a const member function returning `argc_`.

The point is to create an abstraction that’s zero overhead compared to passing `argc` and `argv`.

With a named type, the standard can potentially include `int main(Bundle args);` as a valid declaration of `main`.
The compiler can create `Bundle args` from `argc` and `argv` as a simple transformation.
Of course, a std class will be named different, perhaps `std::args_bundle`. I would say, this would be a better main.

**Comment by eteran** [comment]
@Swat-SomeBug Sure, I totally agree that we can make a standard type to have a "zero overhead" abstraction over it. (The only reason why I put that in quotes is that unfortunately, every access to the bundle will now invoke an implicit `strlen()` or more specifically `Tr::length()` from the `string_view` constructor).

However, my comment was more about an observation I've made about a trend in C++ development lately that I'm not exactly a fan of.

(Sorry minor rant incoming)

There seems to be a desire for C++ developers to write things with as many abstractions as possible, often mimicking the hoops that need to be jumped through to make heavily templated library code work with as many things as possible. And when writing something that needs to be *that* generic, that's a good thing.

But, then I see things like `static_cast<std::ptrdiff_t>(argc)` which actually also made it into @lefticus 's episode and think, "are we trying to make this harder to read?". In this case, the fact is, that `ptrdiff_t` is required by the standard to be:

1. a signed integral type
2. not larger than `signed long int`
3. not smaller than 16-bits (indirect requirement due to `PTRDIFF_MIN` and `PTRDIFF_MAX` definitions).

So casting an  `int` to `ptrdiff_t` AFAICT, does literally nothing. At best, it'll get converted a type that is equal or wider than `int` and will just get sign extended. At worst, now we're unnecessarily truncating the value.

So my reaction is to just say "Yeah, I like this idea, but can we just keep the simple things simple?".

I don't mean to come off as harsh or overly critical. I just think that we as C++ developers can make beautiful code that is expressive, efficient, and easy to understand. We just ... get hung up on the fun of nuances of the standardese too much.

**Comment by eteran** [comment]
@zencatalyst Interesting, but... why? Sure, `operator[]` should always accept something like `ptrdiff_t` or `size_t` so it can deal with large indexes, but the value in this case, by definition **already fits** in an `int`, so casting it to `ptrdiff_t` will only do sign extension, with no change at all to the actual value.

So I mean, is typing an extra 29 characters really worth it when it will literally have no effect on the code at all? Why are we typing ANY code that has no effect at all? What's the justification? It's certainly not clarity as every cast in the code has cognitive overhead of having to understand what it means to cast between the two types. So why is that "better"?

**Comment by milasudril** [comment]
@eteran I have no problem with adding an int to a pointer. A pointer is a point in the address space, an int can represent a vector in the address space. Thus, it makes sense.

**Comment by zencatalyst** [comment]
> casting it to `ptrdiff_t` will only do sign extension, with no change at all to the actual value.

Yes it does a `movsx    rdi, edi`. And it still does this when no static_cast is used.

> So I mean, is typing an extra 29 characters really worth it when it will literally have no effect on the code at all? Why are we typing ANY code that has no effect at all? What's the justification? It's certainly not clarity as every cast in the code has cognitive overhead of having to understand what it means to cast between the two types. So why is that "better"?

It's better since we're being explicit about the cast that is happening behind the scenes. Without the casting the compiler does it implicitly for us. But isn't it better if we too indicate it in our code?

**Comment by eteran** [comment]
> It's better since we're being explicit about the cast that is happening behind the scenes. Without the casting the compiler does it implicitly for us. But isn't it better if we too indicate it in our code?

I'd actually say that it's actually *much* worse.

1. As we've agreed, it doesn't nothing, literally, and does so at the cost of increasing the size of the line of code by 50%!
2. it hurts readability and cognitive overhead. **Every** time a cast is used, the reader has to think to themselves, "how does this effect the value of the thing be casted". And the answer in this case is, "it doesn't".
3. The correct type isn't even necessarily `ptrdiff_t`! This isn't some operator overload where we can look at the function and see the type of the parameter. It's a built in operator that will happily accept any integer type because we're dealing with a `char*` and an `int` which is a well defined operation. In fact, standard says: 
> or one operand shall be a pointer to a completely-defined object type and the other shall have integral or unscoped enumeration type

So the fact that it results in a `movx` is really a platform specific detail that you are elevating to the language level.

4. It's inconsistent in a number of ways. Would you **really** write things like this:

```
int func() { return 5; }
long value = static_cast<long>(func());
// would you really be THIS explicit? Seems absurd to me.
```

or this?

```
int array[] = { 1, 2, 3, 4 };
int value = array[static_cast<ptrdiff_t>(3)]; 
// after all, a[b] is just sugar for *(a + b) 
// and you're arguing that (a + b) should be (a + static_cast<ptrdiff_t>(b) if b is an int, and 3 is in an int.
```

or even this?

```
int num = 10;
long x = 5L * static_cast<long>(num);
```

how about this?

```
int returns_int() { return 5; }
void takes_long(long x) { /* ... */ }
takes_long(static_cast<long>(returns_int());
```

integer promotions are ALL OVER the language and explicitly calling them out in circumstances where they literally *can't* change the value is just silly.

I'm not trying to say that casts should never be used, and I'm certainly not trying to overly critical, I actually compile my code with `-W -Wall -pedantic -Wconversion -Werror` (and a few others too).  But I do think C++ developers are slowly but surely getting worse about writing "write once code" for no good reason.

I'm **all for** explicit casts... when the value can actually change due to the conversion, because if the value can be changed due to the cast, then that is something that needs to be called out. It needs special consideration. So yeah, if `-Wconversion` flags it, I'm definitely writing the cast and possibly adding some code to handle corner cases (eg. unsigned <-> signed conversions).

But writing code as if we're being paid by the character just seems silly to me and wastes time while simultaneously making it harder for someone else to comprehend.

**Comment by zencatalyst** [comment]
@eteran 
Yeah it makes sense. If the standard says it's fine, then it's actually fine. Thanks for sharing your opinion.

**Comment by lefticus** [comment]
Closing because the episode aired, but keep the discussion going if you'd like.
