### ISSUE TITLE
Lambda-only Programming

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#258]
Just for fun, an investigation of using nothing but lambdas, no free functions, no other user defined data structures.

**Comment by JossWhittle** [comment]
Is there an episode on the folding expressions used on lines 17 and 21 of todays video? Struggling to understand what they're expanding to and the docs are not very approachable for this.

**Comment by LB--** [comment]
@JossWhittle the goal if for the lanbda to accept either one or zero paramaeters, so the parameter packs will expand to either nothing, or just the single parameter. The comma operator is used because the last expression in a series of comma operations is the one that is the result of the expression, and since the folds are in an `if constexpr` for when there's only one parameter in the parameter pack, they'll just expand to the parameter.

Here's a demo that may help you better understand:
```cpp
template<typename... Args>
auto getLast(Args&&... args)
{
    return (args, ...);
}
int a = getLast(1, 2, 3, 4); //a == 4
int b = getLast(1, 2, 3); //a == 3
int c = getLast(1, 2); //b == 2
int d = getLast(1); //c == 1
int e = getLast(); //error, return type is void
```

**Comment by lefticus** [comment]
Video link: https://youtu.be/z5ndvveb2qM

**Comment by JossWhittle** [comment]
@LB-- ahh okay. I had thought from the code in the video (https://youtu.be/z5ndvveb2qM?t=387), the intent was that calling `flat_map(1, 2, 3)` would do something with all of them, but it just uses the last element? This is where I was struggling to see how the folding would apply.
