### ISSUE TITLE
transforming lambda captures

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#329]
student asked about how to automatically transform lambda captures into views. We cannot quite do that, but we might be able to get close.

**Comment by lefticus** [comment]
https://compiler-explorer.com/z/9EPnad639

**Comment by LB--** [comment]
I think it would be more useful if the lambda was in the calling code, since you'd want to use this by wrapping existing lambdas and moving the capture list from the lambda to the helper function's argument list so that it can convert them to views and inject them as parameters to the lambda. Perhaps this is a better demo: https://compiler-explorer.com/z/h4n58YscG
```cpp
#include <iostream>
#include <span>
#include <string>
#include <type_traits>

template<typename T>
auto make_view(T const& viewable)
{
    if constexpr(requires { std::basic_string_view{viewable}; })
    {
        return std::basic_string_view{viewable};
    }
    else if constexpr(requires { std::span{viewable}; })
    {
        return std::span{viewable};
    }
    else
    {
        return std::cref(viewable);
    }
}

template<typename L, typename... T>
auto bind_views(L&& lambda, T const&... viewables)
{
    return [lambda = std::forward<L>(lambda), ...viewables = make_view(viewables)]<typename... Args>(Args&&... args)
    {
        return lambda(viewables..., std::forward<Args>(args)...);
    };
}

int main()
{
    std::string s1{"Jason was here"};
    auto explain_jason_behavior = bind_views([](auto s1, auto arg1)
    {
        std::cout << s1 << ' ' << arg1 << '\n';
    }, s1);

    explain_jason_behavior("saying hello to the world");
    explain_jason_behavior("doing some C++ weekly stuff");
}
```
Of course, for a single capture, it may be easier to just use `make_view` directly, but `bind_views` is useful to reduce typing when there are many captures.

**Comment by lefticus** [comment]
Coming in Ep436
