### ISSUE TITLE
What is a template template parameter?

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#76]

**Comment by lefticus** [comment]
See: https://compiler-explorer.com/z/sh45aaj98

**Comment by lefticus** [comment]
example from video: https://compiler-explorer.com/z/nncG6EaqW

**Comment by lefticus** [comment]
Coming in Ep368

**Comment by yephick** [comment]
A fun problem to solve (I'm failing to, thus far...):
USB string descriptors are defined as a "length" byte (*total* size of the descriptor) followed by a descriptor type's byte (0x03 for String) followed by UTF-16 characters. For example:

`enum UsbDescriptorType : uint8_t{
    USB_DESCR_DEVICE                = 1
  , USB_DESCR_CONFIGURATION= 2
  , USB_DESCR_STRING                = 3
 // ... other types
};

struct UsbDescrStd{
    const uint8_t bLength;
    const UsbDescriptorType bDescriptorType;
};

template<size_t N>
struct UsbDescrString: UsbDescrStd{
    char16_t str[N-1]; // [N-1] to allow constructor from C-strings: UsbDescrString(const char(&s)[N])
};`

Now... defining those USB strings in code is a bit cumbersome as it requires me to explicitly provide the size as template argument:
`constinit const UsbDescrString<6>  usbStrManufacturer {"MyLtd"};`

The goal is to provide a user-defined literal that would make that initialization look clean and natural, like this:
`constinit const auto  usbStrManufacturer {"MyLtd"_usbstr};`

The issue here is that I need to provide both template and non-template arguments into the user-defined literal, which is explicitly prohibited by the standard
